apiVersion: v1
kind: PersistentVolumeClaim
##namespace: devops-tools
metadata:
  name: pvc-example
  namespace: devops-tools
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage-retain